modLoader="javafml"
license="CC BY-NC-SA 3.0"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/VazkiiMods/Patchouli"
logoFile="logo.png"

[[mods]]
modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"
authors="Vazkii"
description='''
Accessible, Data-Driven, Dependency-Free Documentation for Minecraft Modders and Pack Makers
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
